#!/bin/bash
echo """#!/bin/bash
#= GEO-dump
#= Download raw sequence data from GEO database
#= This script is generated by command below
#= \$ ~kjyi/bin/geo-dump-help $1 ($1 is a BioProject ID)

#PBS -q long
#PBS -N GEO-download
#PBS -j oe
#PBS -o /dev/null
#PBS -l nodes=1:ppn=1
cd `pwd`
esearch=/home/users/kjyi/tools/kjscript/ws_geo_tools/esearch.sh
efetch=/home/users/kjyi/tools/kjscript/ws_geo_tools/efetch.sh
fastqdump=/home/users/tools/sratoolkit/sratoolkit.2.8.0-centos_linux64/bin/fastq-dump
mkdir -p log
mkdir -p fastq/raw
\$esearch -db sra -query $1 | \$efetch --format runinfo > .tmp
sed 's/,/\t/g' .tmp > .table.tsv
cut -d \",\" -f 1 .tmp | grep SRR | xargs \$fastqdump --disable-multithreading --outdir fastq/raw &> log/dump.log
grep SRR .tmp | awk -F',' '{print \"cat fastq/raw/\"\$1\".fastq >> fastq.\"\$30\".fastq\"}' > rename.sh

exit 0
"""
